version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: docker/images/app/Dockerfile
    ports:
      - '3150:3150'
    depends_on:
      - db
    environment:
      - ENVIRONMENT=DEV
      - NODE_ENV=production
      - PGHOST=db
      - PGUSER=postgres
      - DATABASE_URL=${DATABASE_URL}

  ci:
    build:
      context: .
      dockerfile: docker/images/CI/Dockerfile
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - NODE_ENV=test
    volumes:
      - $PWD/app:/home/node/app
      - $PWD/db:/home/node/db
      - $PWD/config:/home/node/config
      - $PWD/test:/home/node/test
  db:
    image: postgres:12.1
    ports:
      - '5400:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_project_dev
    volumes:
      - /var/run/postgresql:/var/run/postgresql